name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/plopster-land-img:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/plopster-land-img:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          key_passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}  # Si tu clave SSH está protegida por una frase de contraseña
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/plopster-land-img:latest
            docker stop plopster-land-container || true
            docker rm plopster-land-container || true
            docker run -d --name plopster-land-container -p 8001:80 ${{ secrets.DOCKER_USERNAME }}/plopster-land-img:latest
